# Generated by Django 4.1.4 on 2022-12-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='name')),
                ('quantity', models.CharField(blank=True, default='', max_length=300, verbose_name='quantity')),
                ('cost_without_cheat', models.CharField(blank=True, default='', max_length=300, verbose_name='cost_without_cheat')),
                ('cheat', models.CharField(blank=True, default='', max_length=500, verbose_name='cheat')),
                ('total_cost', models.IntegerField(blank=True, default=0, verbose_name='total_cost')),
                ('cost_with_VAT', models.IntegerField(blank=True, default=0, verbose_name='cost_with_VAT')),
                ('total', models.IntegerField(blank=True, default=0, verbose_name='total')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('id',),
            },
        ),
    ]
