# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmptyDialog(object):
    def setupUi(self, EmptyDialog):
        EmptyDialog.setObjectName("EmptyDialog")
        EmptyDialog.resize(400, 300)
        EmptyDialog.setAutoFillBackground(False)
        self.widget = QtWidgets.QWidget(EmptyDialog)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 421, 311))
        self.widget.setObjectName("widget")

        self.retranslateUi(EmptyDialog)
        QtCore.QMetaObject.connectSlotsByName(EmptyDialog)

    def retranslateUi(self, EmptyDialog):
        _translate = QtCore.QCoreApplication.translate
        EmptyDialog.setWindowTitle(_translate("EmptyDialog", "hello world"))
