# Generated by Django 4.1.3 on 2022-11-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter_app', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(blank=True, default=0, max_length=300, verbose_name='user_nickname')),
                ('user_password', models.CharField(blank=True, default='', max_length=300, verbose_name='user_password')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('id',),
            },
        ),
    ]
