# Generated by Django 4.1.3 on 2022-11-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ('id',), 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AlterField(
            model_name='users',
            name='user_nickname',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='user_nickname'),
        ),
    ]
