# Generated by Django 4.1.1 on 2022-11-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0004_alter_users_options_alter_users_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='unique_user_code',
            field=models.IntegerField(blank=True, default=0, verbose_name='unique_user_code'),
        ),
    ]
