# Generated by Django 4.1.1 on 2022-11-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0006_tweets_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='text_tweet',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='text_tweet'),
        ),
    ]
