# Generated by Django 4.1.1 on 2022-11-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0008_alter_tweets_id_alter_users_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='unique_user_code',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='tweets',
            name='author_nickname',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='author_nickname'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
