# Generated by Django 4.1.1 on 2022-11-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(blank=True, default='', max_length=300, verbose_name='user_nickname')),
                ('user_password', models.CharField(blank=True, default='', max_length=300, verbose_name='user_password')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('id',),
            },
        ),
    ]
