# Generated by Django 4.1.3 on 2022-11-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.IntegerField(blank=True, default=0, verbose_name='author_id')),
                ('task_title', models.CharField(blank=True, default='', max_length=300, verbose_name='text_tweet')),
                ('task_description', models.CharField(blank=True, default='', max_length=300, verbose_name='task_description')),
                ('done', models.BooleanField(blank=True, default=False, verbose_name='done')),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задачи',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(blank=True, default='', max_length=300, verbose_name='user_nickname')),
                ('user_password', models.CharField(blank=True, default='', max_length=300, verbose_name='user_password')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('id',),
            },
        ),
    ]
