# Generated by Django 4.1.3 on 2022-11-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='author_id',
        ),
    ]
