# Generated by Django 4.1.3 on 2022-11-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_tasks_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_description',
        ),
    ]
