# Generated by Django 4.1.3 on 2022-11-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tweet', models.IntegerField(blank=True, default=0, verbose_name='id_tweet')),
                ('author_id', models.IntegerField(blank=True, default=0, verbose_name='author_id')),
                ('author_nickname', models.CharField(blank=True, default='', max_length=300, verbose_name='author_nickname')),
                ('text_tweet', models.CharField(blank=True, default='', max_length=300, verbose_name='text_tweet')),
                ('likes', models.IntegerField(blank=True, default=0, verbose_name='likes')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(blank=True, default='', max_length=300, verbose_name='user_nickname')),
                ('user_password', models.CharField(blank=True, default='', max_length=300, verbose_name='user_password')),
                ('user_id', models.IntegerField(blank=True, default=0, verbose_name='unique_user_code')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'ordering': ('id',),
            },
        ),
    ]
