# Generated by Django 4.1.1 on 2022-11-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tweet', models.IntegerField(blank=True, default=0, verbose_name='id_tweet')),
                ('author_id', models.IntegerField(blank=True, default=0, verbose_name='author_id')),
            ],
            options={
                'verbose_name': 'Рейтинг твита',
                'verbose_name_plural': 'Рейтинг твитов',
                'ordering': ('id',),
            },
        ),
    ]
