# Generated by Django 4.1.1 on 2022-11-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0003_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='author_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='user_id'),
        ),
    ]
