# Generated by Django 4.1.1 on 2022-11-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0005_users_unique_user_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tweet', models.IntegerField(blank=True, default=0, verbose_name='id_tweet')),
                ('author_id', models.IntegerField(blank=True, default=0, verbose_name='author_id')),
                ('likes', models.IntegerField(blank=True, default=0, verbose_name='likes')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
