# Generated by Django 4.1.3 on 2022-11-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0009_tweets_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tweet', models.IntegerField(blank=True, default=0, verbose_name='id_tweet')),
                ('user_id', models.IntegerField(blank=True, default=0, verbose_name='user_id')),
            ],
            options={
                'verbose_name': 'Комментарии твита',
                'verbose_name_plural': 'Комментарии твитов',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='tweets',
            name='parent_tweet_id',
            field=models.IntegerField(blank=True, default=None, verbose_name='parent_tweet_id'),
        ),
    ]
