# Generated by Django 4.1.1 on 2022-11-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0012_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet_id', models.IntegerField(blank=True, default=0, verbose_name='tweet_id')),
                ('keyword', models.CharField(blank=True, default='', max_length=60, verbose_name='keyword')),
            ],
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='id_tweet',
            new_name='tweet_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='id_tweet',
            new_name='tweet_id',
        ),
        migrations.RenameField(
            model_name='tweets',
            old_name='id_tweet',
            new_name='tweet_id',
        ),
        migrations.RenameField(
            model_name='tweets',
            old_name='text_tweet',
            new_name='tweet_text',
        ),
    ]
